In [13]:
import numpy as np
import pandas as pd
import scipy.stats as ss

In [14]:
df = pd.DataFrame({"A": ss.norm.rvs(size=10), "B": ss.norm.rvs(size=10), "C":ss.norm.rvs(size=10), "D": np.random.randint(low=0, high=2, size=10)})
df

A         B         C  D
0 -0.059810  0.117016  1.394572  1
1 -1.081935  0.522194 -0.147498  1
2 -0.778713 -0.506380  0.775460  1
3 -0.503465  0.199428 -1.859317  1
4  0.616527 -0.985665 -0.976896  0
5 -0.424168 -0.743020  0.801814  0
6  1.257338 -1.462014  0.303078  1
7  0.091874  0.026138  0.341982  0
8  1.677412 -0.863498 -1.333423  1
9 -0.358356 -0.291586  0.902526  0

In [17]:
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

In [22]:
X = df.loc[:,["A","B","C"]]
Y = df.loc[:, ["D"]]

In [27]:
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel
#过滤思想
skb = SelectKBest(k=2)
skb.fit(X,Y)
skb.transform(X)

C:\Users\HASEE\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 0.11701578,  1.39457223],
       [ 0.52219419, -0.14749764],
       [-0.50637996,  0.77546   ],
       [ 0.19942765, -1.8593167 ],
       [-0.98566537, -0.976896  ],
       [-0.74302026,  0.80181388],
       [-1.46201386,  0.30307804],
       [ 0.0261376 ,  0.34198212],
       [-0.8634975 , -1.3334232 ],
       [-0.29158641,  0.90252577]])

In [28]:
rfe = RFE(estimator = SVR(kernel='linear'),n_features_to_select=2, step=1)
rfe.fit_transform(X,Y)

C:\Users\HASEE\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[-0.05981041,  0.11701578],
       [-1.08193473,  0.52219419],
       [-0.77871288, -0.50637996],
       [-0.5034655 ,  0.19942765],
       [ 0.61652704, -0.98566537],
       [-0.42416831, -0.74302026],
       [ 1.2573379 , -1.46201386],
       [ 0.09187395,  0.0261376 ],
       [ 1.67741189, -0.8634975 ],
       [-0.35835603, -0.29158641]])

In [31]:
#嵌入思想
sfm = SelectFromModel(estimator=DecisionTreeRegressor(), threshold=0.1)
sfm.fit_transform(X,Y)

array([[-0.05981041,  0.11701578],
       [-1.08193473,  0.52219419],
       [-0.77871288, -0.50637996],
       [-0.5034655 ,  0.19942765],
       [ 0.61652704, -0.98566537],
       [-0.42416831, -0.74302026],
       [ 1.2573379 , -1.46201386],
       [ 0.09187395,  0.0261376 ],
       [ 1.67741189, -0.8634975 ],
       [-0.35835603, -0.29158641]])

### 特征预处理